title: Ali G
logo: "/assets/images/headshot.png"
description: "PhD Computational Chemistry | St Andrews | Professor Michael B\"uhl"
theme: jekyll-theme-minimal

author:
 name      : "Ali Goodfellow"
 avatar    : "/assets/images/headshot.png"
 bio       : "PhD Computational Chemistry | St Andrews | Professor Michael B\"uhl"
 location  : "St Andrews, Scotland, UK"
 email     :
 github    : "aligfellow"
 linkedin  : "ali-goodfellow-11b531283"
 twitter   : "ali_goodfellow"
 orcid     : "https://orcid.org/0000-0002-0064-5007"

 
